### ISSUE TITLE
Setup CI so we don't commit breaking changes

### ISSUE THREAD

**Issue by dvdzkwsk** [TechnologyAdvice/ta-react#12]

**Comment by levithomason** [comment]
on it

**Comment by levithomason** [comment]
- [x] added circle.yml
- [x] added build/coverage badges
- [x] setup circle with deweybot SSH keys and NPM token
- [x] protected master branch PRs
- [x] added Slack notifications
- [x] fixed lint packages and lint errors
- [x] got tests passing 👍
