### ISSUE TITLE
exernalHandlers state

### ISSUE THREAD

**Issue by levithomason** [TechnologyAdvice/ta-react#19]
The state passed to an external handler is the state of the external module.  It seems this should actually be the state of the module implementing the external handler.

In my use case, I only need the payload of the external event, not the state of the external module that generated the event.  I need my own state so I can update it.

Is this the correct usage here?  If not, how are you to get your own module's state in an external handler?  Also, why would an external handler get external state when all other handlers get own state, since, both handlers need to return new own state.

**Comment by dvdzkwsk** [comment]
It should be your own state. If it's not, something is borked.

**Comment by levithomason** [comment]
Can't repro, chalking up to user error in someway.
